#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "apt-cacher-ng"
cookbook "build-essential"
# standard library is broken on latest rubies.
cookbook "ruby", :git => "https://github.com/apfritts/ruby-cookbook.git"
cookbook "nodejs"
cookbook 'golang'
cookbook 'leiningen' #clojure
cookbook 'haskell', :git => 'https://github.com/algas/haskell-cookbook.git'
cookbook 'scala'
cookbook 'perl'
cookbook 'python'

cookbook 'yum',:git=>'https://github.com/opscode-cookbooks/yum.git',:ref=>'v2.4.4'